version: '3.7'
services:
  api:
    build: 'password-manager-api/'
    ports:
      - "8080:8080"
    depends_on:
      database:
          condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/password-manager-db
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  frontend:
    build: 'password-manager-frontend/'
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password-manager-db
    healthcheck:
      test: pg_isready -U app
